#!/bin/bash
set -u

NAME="jenkins"
# CONTAINER="jenkins/jenkins"
CONTAINER="jenkins/jenkins:lts"
MOUNTS="`cat /etc/docker-jenkins/mounts.conf`"
EXISTS="yes"
RUNNING="yes"

# Determing if exists and running
echo "Checking container $NAME status..."
RUNNING=$(docker inspect --format="{{ .State.Running }}" $NAME 2> /dev/null)

set -e

if [ $? -eq 1 ]; then
  echo "$NAME does not exist."
  EXISTS="no"
fi

if [ "$RUNNING" == "false" ]; then
  echo "$NAME is not running."
  RUNNING="no"
fi

# stop existing one
if [ "$RUNNING" == "yes" ];
then
  docker stop $NAME || :
fi
# kill it
if [ "$EXISTS" == "yes" ];
then
  docker rm $NAME || :
fi

# run a new container
docker run  \
  -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
  $MOUNTS \
  -p 8080:8080 \
  -p 50000:50000 \
  --name $NAME \
  $CONTAINER
